DROP TABLESPACE DBASPACE INCLUDING CONTENTS;
DROP USER AUDIT_USER CASCADE;
DROP ROLE IT_CHANGEMAN_UPDATE;
DROP ROLE CITI_CONNECT;
DROP ROLE CITI_SCHEMA;
DROP PROFILE SECURITY_PROFILE_FUNCTIONAL CASCADE;
/
